### ISSUE TITLE
Support for restify 5

### ISSUE THREAD

**Issue by karthikiyengar** [maxnachlinger/restify-joi-middleware#19]
With the new version of resitfy, automatic JSON serialization of errors has been removed, unless they're thrown using the restify-errors package: http://restify.com/docs/4to5/

This would mean that any requests failing with a bad request would not return error information to the consumers.

~~I would be happy to send in a PR for this if this is something that you're interested in.~~ - I just looked at the code and this has been already taken care of. The errors are indeed visible in the data property, but for some reason not exposed when the API is called. Am I missing something here?

**Comment by karthikiyengar** [comment]
Since next(err) no longer serializes the error, I got around this by writing a custom errorResponder as follows:
```
errorResponder: (transformedErr, req, res, next) => {
    res.send(400, transformedErr.body);
    return next();
},
```
I believe this can be kept under a flag to let the user decide whether he wants to expose errors to the client or not. I'd be happy to code this up.

**Comment by maxnachlinger** [comment]
@karthikiyengar thanks for investigating this! It looks like the existing `errorResponder` override covers this case right?

**Comment by karthikiyengar** [comment]
@maxnachlinger - Yes, it does work with the override. But it would be nice if it worked out of the box :-)

**Comment by maxnachlinger** [comment]
@karthikiyengar please give version 3 a shot, I've decided to use the error message from joi as the message in the returned error.

**Comment by karthikiyengar** [comment]
@maxnachlinger - I tried version 3. I'm getting the message, but I'm still not receiving the data property - not sure this is what you intended by design. I personally prefer using data, as the message is not that intuitive :-)

```
{
    "code": "BadRequest",
    "message": "child \"body\" fails because [child \"amount\" fails because [\"amount\" is required]]"
}
```

**Comment by maxnachlinger** [comment]
For my part, I prefer meaningful error messages. People disagree, so it goes. I'd just stick with your `errorResponder` override so you can have the results in the format you'd like. You can also fork this library and make all the changes you want - that's what I love about open source :)

**Comment by karthikiyengar** [comment]
Definitely. I'm sticking with my errorResponder, a very nifty extension. Thanks for your great work on the library, I've been using it extensively and it's of great use.
