### ISSUE TITLE
Overriding Joi error messages

### ISSUE THREAD

**Issue by ugolas** [maxnachlinger/restify-joi-middleware#4]
Hi,

Is there a way to override the Joi error messages for my specific validations?

**Comment by maxnachlinger** [comment]
Yes, just implement ``errorTransformer`` when setting up the middleware.
```javascript
server.use(validator({
  convert: true,
  allowUnknown: true,
  abortEarly: false
  // .. all additional joi options
}, {
  errorTransformer: (validationInput, joiError) => {
    return new restifyErrors.BadRequestError('Custom bad request message here')
  }
});
```
If you want specific error messages per item in your validation schema, you can do that with Joi's ``label`` as well. Here's an example: https://github.com/hapijs/joi/blob/master/examples/customMessage.js
