### ISSUE TITLE
Update code to work with restify version 7

### ISSUE THREAD

**Issue by Junkern** [maxnachlinger/restify-joi-middleware#48]
Restify released a new version and has some breaking changes: https://github.com/restify/node-restify/blob/master/CHANGELOG.md

https://github.com/maxnachlinger/restify-joi-middleware/blob/master/index.js#L17 should be updated to `req.route.spec.validation` instead of `req.route.validation`

**Comment by maxnachlinger** [comment]
Thanks for the heads-up! I'll put in a PR shortly

**Comment by maxnachlinger** [comment]
Here's the PR, please have a look: https://github.com/maxnachlinger/restify-joi-middleware/pull/49

**Comment by Junkern** [comment]
Thanks for the quick reaction!

**Comment by maxnachlinger** [comment]
Fix published as version `4.0.1`, let me know if things explode :)
