### ISSUE TITLE
allowUnknown flag does not work as expected

### ISSUE THREAD

**Issue by karthikiyengar** [maxnachlinger/restify-joi-middleware#6]
Here's a quick example to reproduce.

```
const restify = require('restify');
const validator = require('restify-joi-middleware');
const Joi = require('joi');

const server = restify.createServer();
server.use(validator({
  convert: true,
  allowUnknown: false,
  abortEarly: false
}));
server.get({
  url: '/ping/:name',
  validation: {
    params: {
      name: Joi.string().required()
    }
  },
}, (req, res, next) => {
  return res.send({
    message: "Pong " + req.params.name
  });
})
server.listen(8080);
```
Setting allow unknowns to false throws (http://127.0.0.1:8080/ping/) query, headers etc. is not allowed.

Ideally, it should only disallow unknowns for the item that is being validated (params in this case), instead of all of the defaultKeysToValidate.

Let me know your thoughts on this.

**Comment by maxnachlinger** [comment]
Thanks for the issue and the awesome reproduction steps! I agree that for this library, ``allowUnknown`` should mean "Allow unknown properties within the set of keys we're already validating." Please install the latest version via: 
```shell
npm i https://github.com/maxnachlinger/restify-joi-middleware
```
and see if it works for your use case. If it does I'll publish a new version.

**Comment by karthikiyengar** [comment]
Works brilliantly. Can say the same for #5 as well.

Many thanks for the brilliant work and the quick fixes.

**Comment by maxnachlinger** [comment]
Np, version 2.0.0 is now on npm.
