### ISSUE TITLE
Cannot push branch

### ISSUE THREAD

**Issue by johnkariuki** [maxnachlinger/restify-joi-middleware#9]
I'd like to create a new PR for this but I do not have rights to push a new branch.

**Comment by maxnachlinger** [comment]
I'd love a PR :) Normally the way you do it (for any public Github repo) is: 
* fork the repo into your own Github space
* make your awesome changes
* PR them back to this repo

[Here's a more detailed version of the above](http://kbroman.org/github_tutorial/pages/fork.html)
Look forward to your PR.

**Comment by johnkariuki** [comment]
Thank you.
It's actually quite a small update to the ReadME.
